# Rime default settings
# encoding: utf-8

config_version: "0.36"

schema_list:
  - schema: luna_pinyin
  - schema: cangjie5
  - schema: luna_pinyin_fluency
  - schema: luna_pinyin_simp
  - schema: luna_pinyin_tw

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 漢字, 汉字 ]
  - name: ascii_punct
    states: [ 。，, ．， ]

menu:
  page_size: 5

punctuator:
  full_shape:
    ' ' : { commit: '　' }
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : [ 、, ＼ ]
    '|' : [ ·, ｜, '§', '¦' ]
    '`' : ｀
    '~' : ～
    '!' : { commit: ！ }
    '@' : [ ＠, ☯ ]
    '#' : [ ＃, ⌘ ]
    '%' : [ ％, '°', '℃' ]
    '$' : [ ￥, '$', '€', '£', '¥', '¢', '¤' ]
    '^' : { commit: …… }
    '&' : ＆
    '*' : [ ＊, ·, ・, ×, ※, ❂ ]
    '(' : （
    ')' : ）
    '-' : －
    '_' : ——
    '+' : ＋
    '=' : ＝
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕, ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]
  half_shape:
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ 、, '/', ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : [ 、, '\', ＼ ]
    '|' : [ ·, '|', ｜, '§', '¦' ]
    '`' : '`'
    '~' : [ '~', ～ ]
    '!' : { commit: ！ }
    '@' : '@'
    '#' : '#'
    '%' : [ '%', ％, '°', '℃' ]
    '$' : [ ￥, '$', '€', '£', '¥', '¢', '¤' ]
    '^' : { commit: …… }
    '&' : '&'
    '*' : [ '*', ＊, ·, ・, ×, ※, ❂ ]
    '(' : （
    ')' : ）
    '-' : '-'
    '_' : ——
    '+' : '+'
    '=' : '='
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕,  ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]

key_binder:
  bindings:
    # Emacs style
    - { when: composing, accept: Control+p, send: Up }
    - { when: composing, accept: Control+n, send: Down }
    - { when: composing, accept: Control+b, send: Left }
    - { when: composing, accept: Control+f, send: Right }
    - { when: composing, accept: Control+a, send: Home }
    - { when: composing, accept: Control+e, send: End }
    - { when: composing, accept: Control+d, send: Delete }
    - { when: composing, accept: Control+k, send: Shift+Delete }
    - { when: composing, accept: Control+h, send: BackSpace }
    - { when: composing, accept: Control+g, send: Escape }
    - { when: composing, accept: Control+bracketleft, send: Escape }
    - { when: composing, accept: Alt+v, send: Page_Up }
    - { when: composing, accept: Control+v, send: Page_Down }
    # paging keys
    - { when: composing, accept: ISO_Left_Tab, send: Page_Up }
    - { when: composing, accept: Shift+Tab, send: Page_Up }
    - { when: composing, accept: Tab, send: Page_Down }
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }
    # hotkey switch
    - { when: always, accept: Control+Shift+1, select: .next }
    - { when: always, accept: Control+Shift+2, toggle: ascii_mode }
    - { when: always, accept: Control+Shift+3, toggle: full_shape }
    - { when: always, accept: Control+Shift+4, toggle: simplification }
    - { when: always, accept: Control+Shift+5, toggle: extended_charset }
    - { when: always, accept: Control+Shift+exclam, select: .next }
    - { when: always, accept: Control+Shift+at, toggle: ascii_mode }
    - { when: always, accept: Control+Shift+numbersign, toggle: full_shape }
    - { when: always, accept: Control+Shift+dollar, toggle: simplification }
    - { when: always, accept: Control+Shift+percent, toggle: extended_charset }
    - { when: always, accept: Shift+space, toggle: full_shape }
    - { when: always, accept: Control+period, toggle: ascii_punct }

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba

trime:
  keyboard:
  - mode: 0
    ascii_mode: false
    columns: 11
    width: 9
    keys:
    - {symbol: '!', text: '1'}
    - {symbol: '@', text: '2'}
    - {symbol: '#', text: '3'}
    - {symbol: '$', text: '4'}
    - {symbol: '%', text: '5'}
    - {symbol: '^', text: '6'}
    - {symbol: '&', text: '7'}
    - {symbol: '*', text: '8'}
    - {symbol: '(', text: '9'}
    - {symbol: ')', text: '0'}
    - {text: <delete>, width: 10}
    - {text: q}
    - {text: w}
    - {text: e}
    - {text: r}
    - {text: t}
    - {text: y}
    - {text: u}
    - {text: i}
    - {text: o}
    - {text: p}
    - {symbol: '"', text: "'", width: 10}
    - {width: 5}
    - {text: a}
    - {text: s}
    - {text: d}
    - {text: f}
    - {text: g}
    - {text: h}
    - {text: j}
    - {text: k}
    - {text: l}
    - {symbol: ':', text: ';'}
    - {text: <shift>, width: 10, symbolCode: -11}
    - {text: z}
    - {text: x}
    - {text: c}
    - {text: v}
    - {text: b}
    - {text: n}
    - {text: m}
    - {symbol: '<', text: ','}
    - {symbol: '>', text: '.'}
    - {symbol: '?', text: '/'}
    - {label: '123', switch: 1, width: 10, text: <switch>, symbol: '...', symbolCode: -10}
    - {symbol: '~', text: "`"}
    - {symbol: '{', text: '['}
    - {symbol: '}', text: ']'}
    - {text: <space>, width: 18}
    - {symbol: '_', text: '-'}
    - {symbol: '+', text: '='}
    - {symbol: '|', text: '\'}
    - {text: <enter>, symbol: '???', symbolCode: -12, width: 18}
  - mode: 1
    width: 20
    keys:
    - {text: '+'}
    - {text: '1'}
    - {text: '2'}
    - {text: '3'}
    - {text: '#'}
    - {text: '-'}
    - {text: '4'}
    - {text: '5'}
    - {text: '6'}
    - {text: '%'}
    - {text: '*'}
    - {text: '7'}
    - {text: '8'}
    - {text: '9'}
    - {text: ':'}
    - {text: '/'}
    - {text: '±'}
    - {text: '0'}
    - {text: '.'}
    - {text: ','}
    - {text: '='}
    - {text: <switch>, switch: 0}
    - {text: <space>}
    - {text: <delete>}
    - {text: <enter>}
